server:
  port: "8020"

database:
  active: "mongodb" # or "mongodb"

  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: ""
    name: "services_management"

  mongodb:
    host: "department_db"
    port: "27017"
    # user: "Senbox"
    # password: ""
    name: "services_management"

consul:
    host: "localhost"
    port: 8500
    
registry:
  host: "localhost"

